# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

dist: xenial
language: R
cache: packages
warnings_are_errors: false

r_packages:
  - covr
  - mnormt

r_github_packages:
  - jimhester/covr

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required

      r_binary_packages:
        - stringi
        - magrittr
        - curl
        - jsonlite
        - Rcpp
        - bindrcpp
        - RcppEigen
        - rpf
        - mnormt
        - openssl
        - rlang
        - igraph
        - utf8
        - gss
        - haven
        - XML
        - data.table
        - matrixStats
        - carData
        - rgl
        - dplyr
        - purrr
        - tidyr
        - readr
        - minqa
        - mvtnorm
        - nloptr
        - SparseM
        - lme4
        - httpuv
        - markdown
        - OpenMx
        - sem
        - readxl
        - openxlsx
        - pander
        - minpack.lm
        - StanHeaders
        - quantreg
        - forcats
        - ggplot2
        - psych
        - tidyselect
        - pander
        - DT
        - jsonlite
        - future
        - htmltools
        - labeling
        - labelled
        - rstudioapi
        - shiny
        - miniUI
        - glue
        - lubridate
        - rio
        - testthat
        - lme4
        - roxygen2
        - renv
        - webshot

#    - os: osx
#      osx_image: xcode9.2
#    - os: osx
#      osx_image: xcode7.3
#      r_build_args: '--no-build-vignettes'
#      r_check_args: '--ignore-vignettes --no-examples'

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev
    - libgsl0-dev

after_success:
  - Rscript -e 'library(covr); codecov()'


repos:
  CRAN: https://cloud.r-project.org
