# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

r_packages:
  - covr

r_github_packages:
  - jimhester/covr
  - rubenarslan/formr

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev
    - libgsl0-dev

after_success:
  - Rscript -e 'library(covr); codecov()'
